<map version="0.9.0">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node CREATED="1442574539389" ID="ID_174165907" MODIFIED="1442574539389" TEXT="New Mindmap">
<node CREATED="1434139066199" ID="ID_1361208644" MODIFIED="1442575488239" POSITION="right" STYLE="fork" TEXT="Goal: Timely information to Improve Patient Care">
<node CREATED="1434139657810" ID="ID_1404559995" MODIFIED="1442575370124" TEXT="Stakeholder: Secondary Care Clinician">
<node CREATED="1434139689357" ID="ID_1861523975" MODIFIED="1434139727314" TEXT="Capability: Take information from my eDischarge system and send it to the GP electronically">
<node CREATED="1434140069882" ID="ID_625974443" MODIFIED="1442574534055" TEXT="Extract information from outputs generated by eDischarge system">
<node CREATED="1434140247912" ID="ID_1048565638" MODIFIED="1434140354469" TEXT="Parse eDischarge PDF document"/>
<node CREATED="1434140247912" ID="ID_158131988" MODIFIED="1434140357574" TEXT="Parse eDischarge Word document"/>
<node CREATED="1434140247912" ID="ID_335353688" MODIFIED="1434140360973" TEXT="Parse eDischarge Kettering document"/>
<node CREATED="1434140247912" ID="ID_1264623867" MODIFIED="1434140364136" TEXT="Parse arbirtary eDischarge document"/>
</node>
<node CREATED="1434140110709" ID="ID_1615044733" MODIFIED="1434140367870" TEXT="Enrich information from eDischarge system if required">
<node CREATED="1434140385954" ID="ID_1030707436" MODIFIED="1434140397928" TEXT="Look-up patient demographics from PDS"/>
<node CREATED="1434140402270" ID="ID_935006531" MODIFIED="1434140416110" TEXT="Add information about the sending organisation/workgroup"/>
</node>
<node CREATED="1434140161252" ID="ID_1329227777" MODIFIED="1434140371026" TEXT="Create a structured CDA document in-line with national standards"/>
<node CREATED="1434140204958" ID="ID_663204558" MODIFIED="1442574616720" TEXT="Send the document to the patient&apos;s registered GP">
<node CREATED="1434140518456" ID="ID_1843068417" MODIFIED="1434140566155" TEXT="Find the patient&apos;s registered GP on PDS"/>
<node CREATED="1434140533000" ID="ID_489232526" MODIFIED="1434140550770" TEXT="Look-up full GP practice details on SDS"/>
<node CREATED="1434140593907" ID="ID_1454612171" MODIFIED="1434140610485" TEXT="Identify what transports the GP practice can receive documents on"/>
<node CREATED="1434140614146" ID="ID_1232400466" MODIFIED="1434140620251" TEXT="Send the document over the Spine"/>
<node CREATED="1434140614146" ID="ID_937130441" MODIFIED="1434140633775" TEXT="Send the document over ITK Web Services"/>
<node CREATED="1442574618344" ID="ID_1928139821" MODIFIED="1442574632996" TEXT="Send the document over DTS/MESH"/>
</node>
</node>
</node>
<node CREATED="1442575490716" ID="ID_1675031306" MODIFIED="1442575508459" TEXT="Stakeholder: System Administrator">
<node CREATED="1434140685128" ID="ID_1793502773" MODIFIED="1434140771700" TEXT="Capability: Identify failures so a summary can be sent manually">
<node CREATED="1442575558716" ID="ID_882791630" MODIFIED="1442575574378" TEXT="The source document from the eDischarge system cannot be processed"/>
<node CREATED="1442575640558" ID="ID_1144622862" MODIFIED="1442575641507" TEXT="The document requires enrichment with PDS data, but the enrichment fails"/>
<node CREATED="1442575660980" ID="ID_1227142283" MODIFIED="1442575675303" TEXT="A failure occurs when trying to send the document to the GP"/>
</node>
</node>
<node CREATED="1434139192630" ID="ID_926418086" MODIFIED="1442575514793" TEXT="Stakeholder: GP">
<node CREATED="1434139211367" ID="ID_913235504" MODIFIED="1434624224609" TEXT="Capability: Make information about secondary care episodes available to the GP"/>
<node CREATED="1434139257554" ID="ID_13121608" MODIFIED="1434624249430" TEXT="Capability: Incorporate infomation captured in secondary care into GP record"/>
</node>
</node>
</node>
</map>
